### PR TITLE
Correct font on axes and functionality to add axes-labels

### PR DESCRIPTION
**Pull request by Mcpoowl**
Previously the font supplied was only used in the legend. Fixed it so that the font is also used on the Axes.

Furthermore I added the functionality to add a label to the X and Y-axis. Leave empty for no value

### CODE REVIEW

**Comment by Mcpoowl** [comment]
Had some conflicts @JelteMX. Should be solved with my latest commit!

**Comment by JelteMX** [comment]
Cool! Will test it and add it to the widget

**Comment by Mcpoowl** [comment]
Added one more commit @JelteMX . This one adds the functionality to give your charts a title. Since the default fontsize is very small (12px ) I added a property to set the size aswell.

**Comment by JelteMX** [comment]
I'll review the changes this week and push an update to the AppStore :-)

**Comment by Mcpoowl** [comment]
Awesome!

**Pull request merged**
