### PR TITLE
Fix widget early uninitialize

### PR DESCRIPTION
**Pull request by recktenwaldfabian**
Widget is uninitialize'd in Mx7.4 directly after startup.
This prevents that a callback on the destroyed widget causes an exception, when this._numberNode is undefined.

### CODE REVIEW

**Comment by JelteMX** [comment]
I don't see any [changes](https://github.com/mendix/ChartJS/pull/102/files)? What's the fix?

**Comment by JelteMX** [comment]
I just did a test with Mendix 7.4.0. Widgets work as expected, uninitialize is triggered after you move away from the page, so it works. Closing this PR. If you have a test-project that reproduces this issue, please contact Support

**Comment by recktenwaldfabian** [comment]
Hi,
sorry, somehow I forgot the commit,

The problem that I encounter is, that the widget is initialized and directly uninitialized again (only happens in 7.4, probably due to refresh+conditional visibility).
I don’t have a small test project for this yet.

What happens: in a mx.data callback in PieChart.js:111
html.set(this._numberNode, content !== null ? content.toString() : "");

this._numberNode is undefined (probably because the widget is already _destroyed).

The fix would consist of checking if this._destroyed===true before calling _processData.

Can you suggest on how to proceed with this? I’m already spending too much time looking for platform issues and setting up test projects…

**Comment by JelteMX** [comment]
Post your solution in #103 and I'll see if I can use it. The issue makes sense, heard more problems with conditional visibility

**Pull request closed without merging**
